# Generated by Django 3.2 on 2021-04-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='ImageRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='images')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='recipe.recipe')),
            ],
        ),
    ]
